### ISSUE TITLE
Mirrors - add multiple download sources

### ISSUE THREAD

**Issue by Techtribe** [boxen/boxen#100]
While Sourceforge fails sometimes (like with VLC 2.0.7) it would be nice to have a fallback/mirror feature to provide other URLs to use when the ````:source````-property fails.

Something like 
````ruby
:mirrors => ["http://mirror.one","http://mirror.two"]
````

See this [VLC issue](https://github.com/boxen/puppet-vlc/issues/6#issuecomment-20312813) as an example.

**Comment by seanknox** [comment]
I think it might be asking too much of Boxen to be responsible for a third-party's fragile infrastructure. Instead of putting the onus on the end user to try different mirrors until one works, the website should fix their issues. I'm closing this for now, but re-open if you have a convincing case.
