### ISSUE TITLE
MacRuby

### ISSUE THREAD

**Issue by cpetersen** [boxen/boxen#104]
I built a boxen module for MacRuby, I was hoping someone could fork it into the boxen repository so others might benefit. The repo is:

https://github.com/cpetersen/puppet-macruby

Thank you in advance!

**Comment by seanknox** [comment]
@cpetersen Boxen modules need to be request on the https://github.com/boxen/our-boxen repo—can you do so there?

**Comment by mikemcquaid** [comment]
@seanknox Maybe consider moving issues with https://github-issue-mover.appspot.com. A bit more user friendly?

**Comment by seanknox** [comment]
This issue was moved to boxen/our-boxen#745

**Comment by seanknox** [comment]
@mikemcquaid snazzy! thanks.
