### ISSUE TITLE
error installing boxen problem with installer

### ISSUE THREAD

**Issue by rmchale** [boxen/boxen#112]
I get the following error installing boxen:

Error: Execution of '/usr/sbin/installer -pkg /private/tmp/dmg.iCZWzD/XQuartz.pkg -target /' returned 1: installer: Package name is XQuartz 2.7.4
installer: Upgrading at base path /
installer: The upgrade failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

https://gist.github.com/rmchale/6490119

https://gist.github.com/rmchale/6490196 (verbose)

I'm not sure if this is relevant but I have an SSD installed and don't have /Volumes/Macintosh HD, I have another drive that is /Volumes/Boot instead.

**Comment by seanknox** [comment]
Closing this since been a while since it was originally reported. If it's still an issue, feel free to reopen.
