### ISSUE TITLE
Error: Could not find class boxen for <my_host> on node <my_host>

### ISSUE THREAD

**Issue by joshuairl** [boxen/boxen#117]
It says it's installed boxes v2.0.3 via bundler into .bundle directory...
No dice...?

Running Mac OS X 10.9 GM and xcode 5.0.1 seed...

Any tips?

UPDATE: Also note that when I type "which ruby" I'm getting the shim version `/opt/boxen/rbenv/shims/ruby` and I thought I read somewhere that the shim version shouldn't be used in OS X 10.9 due to Ruby 2.0.0 being default on 10.9?  Hmm...?

**Comment by seanknox** [comment]
Closing this since been a while since it was originally reported. If it's still an issue, feel free to reopen.
