### ISSUE TITLE
boxen_user and boxen_home incorrect?

### ISSUE THREAD

**Issue by alastairpat** [boxen/boxen#135]
I'm going to start with saying I'm not 100% certain what I'm doing with Boxen/Puppet but am learning.

I'm trying to create a directory in the user's home directory from a module. According to boxen facts, this should be defined as $::boxen_home (in my case, /Users/atp) and this works when running from site.pp. However, when referenced from my module, it comes up with my github username (/Users/alastairpat) which doesn't work. 

Am I doing something wrong? Sorry if this is a really stupid question…

**Comment by seanknox** [comment]
Instead, `luser` is still on chopping block. Use `"/Users/${::boxen_user}"` in your manifests.
