### ISSUE TITLE
Searching for boxen modules?

### ISSUE THREAD

**Issue by staxmanade** [boxen/boxen#156]
Hey Boxen team!

I know it's only been a day since I posted this over on the website repo, but wanted to mention it here in case some interested parties were not following that repo...

https://github.com/boxen/boxen.github.com/issues/15

Thoughts? (feel free to close here - if it's not a good place to discuss...)

**Comment by seanknox** [comment]
@staxmanade that looks useful! Going to close here but would recommend ping someone in that repo thread.
