### ISSUE TITLE
Setting homebrew_root to /usr/local results in persistent preflight warnings

### ISSUE THREAD

**Issue by phinze** [boxen/boxen#172]
Looks like `Boxen::Preflight::Homebrew` will complain if, `/usr/local/Library/Homebrew` exists, but now that the Homebrew location is configurable this is not always worth warning about.

Could try to plumb the configured value of homebrew_root down to the preflight check, or could just remove this particular preflight check. Not sure which makes more sense. :8ball:

**Comment by mikemcquaid** [comment]
> Could try to plumb the configured value of homebrew_root down to the preflight check, or could just remove this particular preflight check. Not sure which makes more sense.

I think removing it makes more sense, personally.

**Comment by dgoodlad** [comment]
> I think removing it makes more sense, personally.

:+1:
