### ISSUE TITLE
Oauth Error after I enter my Github credentials

### ISSUE THREAD

**Issue by IAMRYO** [boxen/boxen#180]
Trying to use Boxen to set up a new MBP and keep receiving the following error: 

    --> Something went terribly wrong.
        I was able to get your OAuth token, but was unable to use it.

Not really sure how to proceed. Any help would be much appreciated.

**Comment by seanknox** [comment]
Hey @IAMRYO! Me too. :)

**Comment by seanknox** [comment]
@IAMRYO Try deleting your Boxen personal access token in your GitHub settings. That seems to move it along, at least.

**Comment by IAMRYO** [comment]
Bam! That did it! Thanks @seanknox

**Comment by bryankennedy** [comment]
There's a [better description of the workaround on this issue](https://github.com/boxen/boxen/issues/182#issuecomment-99208353).
