### ISSUE TITLE
OAuth error when using same GitHub account on multiple computers

### ISSUE THREAD

**Issue by seanknox** [boxen/boxen#182]
I have multiple workstations with the same configuration using the same GitHub account to authenticate. Recently, after running Boxen on one computer, the remaining computers are unable to use the token. The only way to run Boxen again is to delete the account's personal application token on GitHub.

```
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
--> Oh, looks like you've provided your login as environmental variable...

GitHub password: *****************

--> Something went terribly wrong.
    I was able to get your OAuth token, but was unable to use it.
```

**Comment by rafaelfranca** [comment]
Very weird. I use the same account in three different machines and all are working fine. Does this happen every time?

**Comment by seanknox** [comment]
Yes, and just started happening as far as I can tell. Using boxen gem version 2.7.1, latest `puppet-boxen` release.

**Comment by mastahyeti** [comment]
Probably related to a [recent GitHub API change](https://developer.github.com/changes/2015-04-20-authorizations-api-response-changes-are-now-in-effect/). The affected code is [here](https://github.com/boxen/boxen/blob/5a8634aa7b7ada58b94cfaceb04ff668bf478502/lib/boxen/preflight/creds.rb#L49-90).

**Comment by ptoomey3** [comment]
I think this could be related to the Authorizations API changes that we recently shipped on GitHub: https://developer.github.com/changes/2015-04-20-authorizations-api-response-changes-are-now-in-effect/. Specifically, it looks like [this code](https://github.com/boxen/boxen/blob/5a8634aa7b7ada58b94cfaceb04ff668bf478502/lib/boxen/preflight/creds.rb#L85-L92) assumes you can access the plaintext token for an existing authorization. That is no longer the case. Instead, the app needs to manage tokens using a `fingerprint` (ex. a SHA256 of the machine's MAC address would suffice). Each time a user logs in from a given machine you can use the fingerprint to see if there is an authorization that already exists for that machine, delete it if there is, and then create a new one. We made this change to bolster security related to the Authorizations API.

**Comment by neckhair** [comment]
As a workaround I just renamed the Description of the existing token to something like "Boxen MBP Home". That worked for now.

**Comment by eshaham** [comment]
@neckhair can you elaborate? how did you manage to create a workaround?

**Comment by neckhair** [comment]
@eshaham Goto https://github.com/settings/tokens and rename the "Boxen" token. Then run `boxen` on the new Mac. After that there will be a second token which you can rename as well if you like. That worked for me.

**Comment by eshaham** [comment]
@neckhair Got it, working for me. Thanks!

**Comment by bryankennedy** [comment]
[neckhair's fix](https://github.com/boxen/boxen/issues/182#issuecomment-99208353) worked for me as well. In the short term, maybe this could get documented in the readme?

**Comment by seanknox** [comment]
Thanks @neckhair for documenting a workaround here.

The real fix is to update Boxen to use the GitHub's new Authorizations API. I haven't had time to take a crack at it yet. PRs welcome. :)

**Comment by newmerator** [comment]
i think it worked, @seanknox might wanna try running boxen now.
