### ISSUE TITLE
Warning when running Boxen on 10.11/El Capitan

### ISSUE THREAD

**Issue by weyert** [boxen/boxen#192]
I have installed El Capitan (OS X 10.11) on one of my Macs. Only I am getting the warning:
You must be running one of the following OS X versions: 10.8 10.9 10.10.

Any plans to support Boxen on 10.11?

**Comment by akerl** [comment]
What version of the boxen gem are you using? 2.8.0 added "support" for 10.11: https://github.com/boxen/boxen/blob/2.8.0/lib/boxen/preflight/os.rb

**Comment by weyert** [comment]
Yes, I noticed that too. Looks like our-Biden when you check it out now is using an older version. Made it work now!

Thanks
