### ISSUE TITLE
Problems after El Capitain upgrade

### ISSUE THREAD

**Issue by ogenstad** [boxen/boxen#194]
I upgraded a Mac to 10.11 and ran into a problem with the OS not being supported. I then upgraded to Boxen 2.8.0 in the Gemfile but didn't get in to work. On another Mac running 10.10 it's working fine after the 2.8.0 upgrade. I don't know if it's the only problem but the first thing Boxen is complaining about is rake. I'm guessing something is pointing to the wrong path but I'm not quite sure where to look.

Does anyone have any suggestions?

The output below is what I'm seeing, would any other output be helpful?

patrick at ns2803m in ~
$ boxen
--> Preparing to auto-update...
/Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `map!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `materialize'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/definition.rb:133:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/definition.rb:178:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/definition.rb:167:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/environment.rb:18:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:13:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler.rb:119:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/setup.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from config/basic.rb:23:in `<top (required)>'
	from /opt/boxen/bin/boxen-git-credential:28:in `load'
	from /opt/boxen/bin/boxen-git-credential:28:in `<main>'
Password for 'https://ogenstad@bitbucket.org':
/Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `map!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `materialize'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/definition.rb:133:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/definition.rb:178:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/definition.rb:167:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/environment.rb:18:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/runtime.rb:13:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler.rb:119:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.5.3/lib/bundler/setup.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from config/basic.rb:23:in `<top (required)>'
	from /opt/boxen/bin/boxen-git-credential:28:in `load'
	from /opt/boxen/bin/boxen-git-credential:28:in `<main>'
--> Complete! Nothing new from upstream.
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
Could not find rake-10.3.2 in any of the sources
Run `bundle install` to install missing gems.

patrick at ns2803m in ~
$ rake -V
rake, version 10.3.2

patrick at ns2803m in ~
$ cd src/our-boxen

patrick at ns2803m in ~/src/our-boxen (master)
$ rake -V
Could not find rake-10.3.2 in any of the sources
Run `bundle install` to install missing gems.

**Comment by mjio** [comment]
I'm having the same issue. Have you been able to find a solution yet?

**Comment by ogenstad** [comment]
No I haven't found any solution yet. I have an older laptop which was running Mavericks where Boxen was working. After I upgraded that one to El Capitain everything worked as my Boxen version already was at 2.8.0.

So I tested to run the Boxen nuke program to wipe it clean and then reinstall Boxen. My thinking was that I would do the same think with my current laptop it it worked. This seemed to solve the problem. However I run into another one as the current boxen-nginx [doesn't work with El Capitain](https://github.com/boxen/puppet-nginx/pull/45). When/if that patch gets commited I will try again with my old laptop. If I get that to work I'll nuke my new one and just reinstall Boxen.

But if there's a solution to the rake issue that's my first option. Don't know what to do about that though. Please let me know if you find anything.

**Comment by timdorr** [comment]
First make sure you've got the command line tools installed. Mine just disappeared after upgrading. You can get them back with `xcode-select --install`.

As for the bundler issue, it appears to no longer be installed under 10.11. You can no longer `sudo gem install bundler` because of System Integrity Protection (SIP). You may be able to install it under `/usr/local/bin`, which is allowed writable by SIP. However, if you must disable it (**really, don't do this!**), you can boot into recovery mode and type `csrutil disable` into Terminal. Then you can install bundler and it should work A-OK.

**Comment by ogenstad** [comment]
Thank you for your suggestions. I tried running the xcode-select --install command but the tools are already installed: "xcode-select: error: command line tools are already installed, use "Software Update" to install updates".

I don't get any warnings when running sudo gem install bundler, and it looks like the command is working but it doesn't help.

Looking at the output from the below commands it looks like I have the correct version of rake installed but that boxen is using the wrong version. 

patrick at ns2803m in ~
$ which rake
/opt/boxen/rbenv/shims/rake

patrick at ns2803m in ~
$ rake -V
rake, version 10.3.2

patrick at ns2803m in ~
$ cd src/our-boxen

patrick at ns2803m in ~/src/our-boxen (master)
$ which rake
bin/rake

patrick at ns2803m in ~/src/our-boxen (master)
$ rake -V
Could not find rake-10.3.2 in any of the sources
Run `bundle install` to install missing gems.

patrick at ns2803m in ~/src/our-boxen (master)
$

If I run "bundle install" from my repo directory I'm able to run "rake -V" from that directory. But when I run boxen again it's the same error and after that rake -V gives the same error "Could not find rake-10.3.2 in any of the sources"

The difference is that after the "bundle install" command the first line of bin/rake is "#!/usr/bin/ruby" after I run boxen the first line is "#!/usr/bin/env ruby"

**Comment by ogenstad** [comment]
I edited the bin/rake file with vi and set the first line to: #!/usr/bin/ruby

This fixed the problem. So now I'm able to run Boxen again.

**Comment by stephenyeargin** [comment]
Running `bundle exec script/bootstrap` seems to have moved me further down the line.

**Comment by dmcnaught** [comment]
I was seeing this error with `git pull` after an upgrade to High Sierra.
I saw that it didn't happen for all projects.
Going into .git/config and changing `url = https://github.com...` to `url = git@github.com:` got rid of the error.
