### ISSUE TITLE
Proposal to drop Ruby 1.8.7 support

### ISSUE THREAD

**Issue by jacobbednarz** [boxen/boxen#202]
We currently have a [failing build](https://travis-ci.org/boxen/boxen/jobs/143221095) due to the [JSON gem requiring Ruby > 2.0](https://github.com/flori/json/blob/v2.0.1/json.gemspec#L21). We have a couple of options here:

- **Pin to a specific version of the JSON gem that allows 1.8.7 support.** I haven't looked into how old the version of the gem would be but I can imagine there has been a fair amount of development on it since and we would be taking quite a step backwards to support this. 
- **Remove 1.8.7 support from Boxen.** All my findings are pointing at Mountain Lion being the last version to ship with 1.8.7 as it's default (which is now 3 releases from latest at the time of writing). Removing 1.8.7 support would then put us in at least Ruby 2.0 world and would pave the way for some improvements and tidy up in the codebase that needed to account for the older Ruby cases.

I'm voting we take the second option so that we can keep progressing forward. I'm interested to hear other opinions as well as what we should consider a supported version of OSX (latest minus 3?)

**Comment by dgoodlad** [comment]
:+1: for dropping 1.8.7 support.

**Comment by jacobbednarz** [comment]
Pull request for this one is in #204
