### ISSUE TITLE
Deprecate puppet modules in favour of brewcask

### ISSUE THREAD

**Issue by jacobbednarz** [boxen/boxen#203]
The Boxen organisation has **a lot** of puppet modules that do something along the following lines:

``` puppet
class myapplication {
  package { 'myapplication':
    provider => 'appdmg',
    source   => "http://downloads.domain.com/myapplication.dmg"
  }
}
```

While this isn't necessarily bad, it can be better achieved by using `boxen::personal::osx_apps` (synonymous to `boxen::personal::casks`) which uses brewcask under the hood and is quite well supported. This also saves the `boxen/our-boxen` Puppetfile from getting ridiculously long when you fork it for your team and everyone wants 100 of their own personal favourites to be installed.

Over the coming weeks I'm going to be opening issues against any Boxen `puppet-*` repositories that meet the above criteria and can be substituted with brewcask. I'll do up a little explanation with the following included:
- Why this is happening (rehash of the above information)
- Date of removal and deprecation policy
- Updated text for their README to instruct users the module will be disappearing and how to use Boxen + brewcask with a puppet manifest and hiera

Is there anything else (steps/information/objections) to consider here?

**Comment by MikeMcQuaid** [comment]
@jacobbednarz I thought I'd pop in and see how Boxen was doing without me/GitHub and just wanted to say I think you're doing a great job. Well done ⚡️ ❤️ 👍

**Comment by jacobbednarz** [comment]
@MikeMcQuaid thanks! I appreciate it! 🎈
