### ISSUE TITLE
Boxen Fails to Install on macOS 10.13

### ISSUE THREAD

**Issue by AlanBreck** [boxen/boxen#218]
Hello,

Getting the following error when attempting to install boxen on macOS 10.13:

```
Jacobs-MacBook-Pro:repo jacoblamont$ ./script/boxen
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
GitHub login: |jacoblamont| alanbreck
GitHub password: ****************
--> You must be running one of the following OS X versions: 10.8 10.9 10.10 10.11 10.12.
```

Will support for 10.13 be coming?

**Comment by jacobbednarz** [comment]
@webflo has started work on this in #215 so feel free to follow along with that. If you want to bypass this check, you [skip the OS check](https://github.com/boxen/boxen/blob/master/lib/boxen/preflight/os.rb#L31) entirely but YMMV since it's not supported yet.
