### ISSUE TITLE
Applescript, App Store and Xcode?

### ISSUE THREAD

**Issue by phs** [boxen/boxen#90]
How would you guys feel about automating Xcode installation from the app store?

It appears possible to [programmatically enable support for assistive devices](https://gist.github.com/phs/5692872) and use apple script to [drive the app store around](https://gist.github.com/phs/5693053).  The underlying API is meant to aid people who physically can't move a mouse or read a screen, so I strongly suspect it would eventually be able to enter an iTunes password and click yes on a EULA.

Deeper integration (i.e creating `boxen/puppet-applescript` and letting things depend on it) would probably unlock further achievements re: configuring uncooperative apps.

I'm happy to hack up a PR, but blindly automating an app store install is perhaps a little too Dark Side.  That's what I want to talk about.  My initial thought is to introduce a keychain entry named `I_ACCEPT_THE_XCODE_EULA` or `I_ACCEPT_ALL_EULAS`.  Have `boxen-web` (or the `scripts/boxen` CLI) prompt for a yes and iTunes creds (which also goes into the keychain.)  Then we're off to the races.

Whatcha think?

**Comment by mikemcquaid** [comment]
Passing on this as I'm also not comfortable with the security implications. `brew cask` is the next best thing until we can convince Apple to get us a CLI to access the App Store.

**Comment by xdissent** [comment]
Maintenance on this has been heinous. I agree wholeheartedly with your assessment. Cask away in the meantime and pray/lobby for App Store cli.
