### ISSUE TITLE
Display appropriate error message if a module tag version was not found

### ISSUE THREAD

**Issue by salimane** [boxen/boxen#97]
If a module tag version was wrongly specifed in the Puppetfile, boxen fails without giving any clue as to what was the problem. Refer to [#313](https://github.com/boxen/our-boxen/issues/313)
Thanks

**Comment by jacobbednarz** [comment]
@salimane #313 isn't working for me? Are you able to point me at the issue you're referring to? Otherwise I'm happy to close.

**Comment by salimane** [comment]
The issue I was referring to was that when a tag specified in the puppetfile that does not exist, boxen fails without any meaningful error message.

**Comment by jacobbednarz** [comment]
If I understand correctly, this isn't really a Boxen issue since the dependencies are managed by puppet-librarian. I gather the error message you get is a "X isn't defined or available" type of thing?

**Comment by salimane** [comment]
yep true , this is a puppet-librarian thing, I will close this issue here. Thanks @jacobbednarz
