### ISSUE TITLE
403 responses downloading Puppet modules with GitHub Enterprise

### ISSUE THREAD

**Issue by mdelagrange** [boxen/boxen#99]
This is a known issue with the GitHub API. (See #83). The solution to this for public GitHub users is to set an oAuth token to raise the rate limit for API requests, but GitHub Enterprise users cannot do this. How can we make module downloading reliable for Enterprise users?

**Comment by jacobbednarz** [comment]
@mdelagrange thanks for the report and apologies for the radio silence - I'm just brooming some of the issues now and came across this one. Is this still an issue? If so, I'm happy to spend some time getting this to be a better experience for GitHub Enterprise users.
